#!/bin/bash
FILEDIR=../dist/ijcb_paper_`date +%Y_%m_%d_%H_%M`
FILENAME=$FILEDIR.zip
echo "Archiving to directory $FILEDIR..."
git archive --output $FILENAME master
#mkdir $FILEDIR
#git archive master | tar -x -v -C $FILEDIR
#echo "Removing $FILEDIR/results to save space..."
#rm -rf $FILEDIR/results
#echo "Compressing "

echo ""
echo ""
echo "Hello Allen and Victor-"
echo ""
echo "I have uploaded an archive of our IJCB paper to:"
echo ""
echo "http://cpanel.cs.illinois.edu/~percept/Hidden/drew/$FILENAME"
echo ""
echo "Cheers,"
echo "Drew"

echo ""
echo ""
echo ""
echo "Uploading..."
scp $FILENAME percept@cpanel.cs.illinois.edu:public_html/Hidden/drew/$FILENAME
echo "Done..."
